import React from 'react';
import { View, Text, Pressable, Linking } from 'react-native';
import { AlertTriangle, Info, ExternalLink } from 'lucide-react-native';
import Animated, { FadeIn } from 'react-native-reanimated';

interface DisclaimerProps {
  variant?: 'banner' | 'inline' | 'modal';
  onDismiss?: () => void;
}

/**
 * Legal disclaimer component for mock voting compliance
 * Per FEC requirements: clear and conspicuous disclaimer on digital platforms
 */
export function MockVotingDisclaimer({ variant = 'banner', onDismiss }: DisclaimerProps) {
  const handleLearnMore = () => {
    Linking.openURL('https://www.fec.gov/help-candidates-and-committees/advertising-and-disclaimers/');
  };

  if (variant === 'inline') {
    return (
      <View className="flex-row items-center px-3 py-2 bg-amber-900/20 rounded-lg border border-amber-700/30">
        <Info size={14} color="#F59E0B" />
        <Text className="text-amber-400 text-xs ml-2 flex-1">
          Mock vote only. Does not affect actual legislation.
        </Text>
      </View>
    );
  }

  return (
    <Animated.View
      entering={FadeIn}
      className="mx-4 mb-4 bg-slate-800/90 rounded-xl border border-slate-700 overflow-hidden"
    >
      <View className="flex-row items-center px-4 py-3 bg-amber-900/30 border-b border-amber-700/30">
        <AlertTriangle size={18} color="#F59E0B" />
        <Text className="text-amber-400 font-semibold ml-2">
          Educational Platform Notice
        </Text>
      </View>

      <View className="p-4">
        <Text className="text-slate-300 text-sm leading-5 mb-3">
          AYE & NAY is an <Text className="font-semibold text-white">educational mock-voting platform</Text>.
          Votes cast here have <Text className="font-semibold text-white">no effect</Text> on actual legislation
          or official government processes.
        </Text>

        <Text className="text-slate-400 text-xs leading-4 mb-3">
          This platform is not affiliated with any government agency, political party, or election
          authority. All legislative data is sourced from public records for educational purposes only.
        </Text>

        <View className="flex-row items-center justify-between">
          <Pressable
            onPress={handleLearnMore}
            className="flex-row items-center"
          >
            <Text className="text-amber-500 text-sm mr-1">Learn More</Text>
            <ExternalLink size={12} color="#F59E0B" />
          </Pressable>

          {onDismiss && (
            <Pressable
              onPress={onDismiss}
              className="bg-slate-700 px-4 py-2 rounded-lg"
            >
              <Text className="text-white text-sm font-medium">Understood</Text>
            </Pressable>
          )}
        </View>
      </View>
    </Animated.View>
  );
}

/**
 * Bill accuracy indicator showing when data was last synced
 */
export function BillVersionIndicator({
  lastUpdated,
  source,
}: {
  lastUpdated: string;
  source: 'congress.gov' | 'govinfo' | 'propublica';
}) {
  const sourceLabels = {
    'congress.gov': 'Congress.gov API',
    'govinfo': 'GovInfo API',
    'propublica': 'ProPublica API',
  };

  const formattedDate = new Date(lastUpdated).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });

  return (
    <View className="flex-row items-center px-3 py-1.5 bg-slate-800/60 rounded-full">
      <View className="w-2 h-2 rounded-full bg-emerald-500 mr-2" />
      <Text className="text-slate-400 text-xs">
        Data from {sourceLabels[source]} • Updated {formattedDate}
      </Text>
    </View>
  );
}

/**
 * AI-generated content disclaimer
 */
export function AIContentDisclaimer() {
  return (
    <View className="flex-row items-start px-3 py-2 bg-purple-900/20 rounded-lg border border-purple-700/30">
      <View style={{ marginTop: 2 }}>
        <Info size={14} color="#A855F7" />
      </View>
      <View className="flex-1 ml-2">
        <Text className="text-purple-400 text-xs font-medium mb-0.5">
          AI-Generated Summary
        </Text>
        <Text className="text-slate-400 text-xs leading-4">
          This summary was generated by AI to improve readability.
          Always review the official text for accuracy.
        </Text>
      </View>
    </View>
  );
}

/**
 * Not official voting warning for bill detail pages
 */
export function NotOfficialVoteWarning() {
  return (
    <View className="flex-row items-center justify-center py-2 bg-red-900/20 border-t border-red-700/30">
      <AlertTriangle size={14} color="#EF4444" />
      <Text className="text-red-400 text-xs ml-2">
        This is NOT an official vote • For educational purposes only
      </Text>
    </View>
  );
}

/**
 * First-time user agreement modal content
 */
export function UserAgreementContent() {
  return (
    <View className="p-4">
      <Text className="text-white font-bold text-xl mb-4">
        Welcome to AYE & NAY
      </Text>

      <Text className="text-slate-300 leading-5 mb-4">
        Before you continue, please understand:
      </Text>

      <View className="space-y-3 mb-6">
        <AgreementPoint
          title="Mock Voting Only"
          description="Votes here are simulated and do not affect actual legislation."
        />
        <AgreementPoint
          title="Educational Purpose"
          description="This platform exists to help citizens understand the legislative process."
        />
        <AgreementPoint
          title="No Government Affiliation"
          description="AYE & NAY is not affiliated with any government entity or election authority."
        />
        <AgreementPoint
          title="Data Sources"
          description="Legislative data comes from public APIs including Congress.gov and GovInfo."
        />
        <AgreementPoint
          title="AI Assistance"
          description="Some content is summarized using AI. Always verify with official sources."
        />
      </View>

      <Text className="text-slate-500 text-xs leading-4">
        By using AYE & NAY, you acknowledge that this is an educational platform
        and that your mock votes have no legal or governmental effect. For official
        voting information, visit vote.gov.
      </Text>
    </View>
  );
}

function AgreementPoint({ title, description }: { title: string; description: string }) {
  return (
    <View className="flex-row items-start mb-3">
      <View className="w-2 h-2 rounded-full bg-amber-500 mt-1.5 mr-3" />
      <View className="flex-1">
        <Text className="text-white font-medium mb-0.5">{title}</Text>
        <Text className="text-slate-400 text-sm">{description}</Text>
      </View>
    </View>
  );
}
