-- Accounts for the B2B analytics portal.
--
-- Additive only: one CREATE TABLE and two CREATE UNIQUE INDEX. No DROP, no
-- ALTER, no existing row read or written.
--
-- Idempotent on purpose. Prisma does not emit IF NOT EXISTS, and a migration
-- that cannot tolerate its own objects already existing is one that fails at
-- the worst possible moment — this project has already lost a deploy to exactly
-- that (42701, re-running against a database that already had the objects).
--
-- The table is created EMPTY. Accounts are written by scripts/seed-b2b.ts,
-- which reads the six B2B_* variables and hashes before inserting; no
-- credential is ever carried in a migration.
--
-- Generated by `prisma migrate dev` against a throwaway local Postgres
-- (127.0.0.1:5433, database `b2bclients`) and then guarded by hand. The column
-- list below is Prisma's own output, unmodified.

-- CreateTable
CREATE TABLE IF NOT EXISTS "B2BClient" (
    "id" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "tier" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "apiKeyHash" TEXT NOT NULL,
    "lastAccessAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "B2BClient_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "B2BClient_username_key" ON "B2BClient"("username");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "B2BClient_apiKeyHash_key" ON "B2BClient"("apiKeyHash");
