-- Sessions for the B2B analytics portal.
--
-- Additive only: one CREATE TABLE and two CREATE INDEX. No DROP, no ALTER, and
-- no existing row is read or written. Nothing that exists before this runs is
-- changed by it.
--
-- Idempotent on purpose. Prisma does not emit IF NOT EXISTS, and a migration
-- that cannot tolerate its own objects already existing is one that fails at
-- the worst possible moment — this project has already lost a deploy to exactly
-- that (42701, re-running against a database that already had the objects).
--
-- Generated by `prisma migrate dev` and then guarded by hand. The column list
-- below is Prisma's own output, unmodified.

-- CreateTable
CREATE TABLE IF NOT EXISTS "B2BSession" (
    "token" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "clientName" TEXT NOT NULL,
    "tier" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "B2BSession_pkey" PRIMARY KEY ("token")
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "B2BSession_clientId_idx" ON "B2BSession"("clientId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "B2BSession_expiresAt_idx" ON "B2BSession"("expiresAt");
