// Comprehensive Government Data - All 3 Branches
// Data Sources:
// - Legislative: Congress.gov API (https://api.congress.gov)
// - Executive: Federal Register API (https://www.federalregister.gov/developers/documentation/api/v1)
// - Judicial: CourtListener/SCDB (https://www.courtlistener.com/help/api/, http://scdb.wustl.edu/)

import type {
  Bill,
  ExecutiveOrder,
  SupremeCourtCase,
  Justice,
  Representative,
  User,
  FeedItem,
  BillCategory,
} from './types';
import { representatives } from './mock-data';

// ==========================================
// SUPREME COURT JUSTICES (Current Court)
// ==========================================

export const justices: Justice[] = [
  {
    id: 'roberts',
    name: 'John G. Roberts Jr.',
    appointedBy: 'George W. Bush',
    appointedYear: 2005,
    isChiefJustice: true,
    imageUrl: 'https://www.supremecourt.gov/about/images/JGRoberts.jpg',
    ideology: 'conservative',
  },
  {
    id: 'thomas',
    name: 'Clarence Thomas',
    appointedBy: 'George H.W. Bush',
    appointedYear: 1991,
    isChiefJustice: false,
    imageUrl: 'https://www.supremecourt.gov/about/images/CThomas.jpg',
    ideology: 'conservative',
  },
  {
    id: 'alito',
    name: 'Samuel A. Alito Jr.',
    appointedBy: 'George W. Bush',
    appointedYear: 2006,
    isChiefJustice: false,
    imageUrl: 'https://www.supremecourt.gov/about/images/SAlito.jpg',
    ideology: 'conservative',
  },
  {
    id: 'sotomayor',
    name: 'Sonia Sotomayor',
    appointedBy: 'Barack Obama',
    appointedYear: 2009,
    isChiefJustice: false,
    imageUrl: 'https://www.supremecourt.gov/about/images/SSotomayor.jpg',
    ideology: 'liberal',
  },
  {
    id: 'kagan',
    name: 'Elena Kagan',
    appointedBy: 'Barack Obama',
    appointedYear: 2010,
    isChiefJustice: false,
    imageUrl: 'https://www.supremecourt.gov/about/images/EKagan.jpg',
    ideology: 'liberal',
  },
  {
    id: 'gorsuch',
    name: 'Neil M. Gorsuch',
    appointedBy: 'Donald Trump',
    appointedYear: 2017,
    isChiefJustice: false,
    imageUrl: 'https://www.supremecourt.gov/about/images/NGorsuch.jpg',
    ideology: 'conservative',
  },
  {
    id: 'kavanaugh',
    name: 'Brett M. Kavanaugh',
    appointedBy: 'Donald Trump',
    appointedYear: 2018,
    isChiefJustice: false,
    imageUrl: 'https://www.supremecourt.gov/about/images/BKavanaugh.jpg',
    ideology: 'conservative',
  },
  {
    id: 'barrett',
    name: 'Amy Coney Barrett',
    appointedBy: 'Donald Trump',
    appointedYear: 2020,
    isChiefJustice: false,
    imageUrl: 'https://www.supremecourt.gov/about/images/ABarrett.jpg',
    ideology: 'conservative',
  },
  {
    id: 'jackson',
    name: 'Ketanji Brown Jackson',
    appointedBy: 'Joe Biden',
    appointedYear: 2022,
    isChiefJustice: false,
    imageUrl: 'https://www.supremecourt.gov/about/images/KJackson.jpg',
    ideology: 'liberal',
  },
];

// ==========================================
// EXECUTIVE ORDERS (Real EOs from Federal Register)
// ==========================================

export const executiveOrders: ExecutiveOrder[] = [
  // Trump 2025 Executive Orders
  {
    id: 'eo-14147',
    eoNumber: 'EO 14147',
    title: 'Declaring a National Emergency at the Southern Border of the United States',
    shortTitle: 'Border Emergency Declaration',
    president: 'Donald J. Trump',
    signedDate: '2025-01-20',
    publishedDate: '2025-01-22',
    status: 'active',
    category: 'immigration',
    federalRegisterNumber: '2025-01532',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/22/2025-01532/declaring-a-national-emergency-at-the-southern-border',
    fullText: 'By the authority vested in me as President by the Constitution and the laws of the United States of America, including the National Emergencies Act (50 U.S.C. 1601 et seq.), I hereby declare that a national emergency exists at the southern border of the United States...',
    simplifiedText: 'This executive order declares a national emergency at the U.S.-Mexico border, enabling the use of military resources and funding to address illegal immigration and drug trafficking.',
    realWorldImpact: 'Allows deployment of military personnel to the border, redirects federal funding to border security, and enables faster construction of physical barriers.',
    communityVotes: { yea: 34200, nay: 41800, totalVoters: 76000 },
    branch: 'executive',
  },
  {
    id: 'eo-14148',
    eoNumber: 'EO 14148',
    title: 'Protecting the American People Against Invasion',
    shortTitle: 'Immigration Enforcement Order',
    president: 'Donald J. Trump',
    signedDate: '2025-01-20',
    publishedDate: '2025-01-22',
    status: 'active',
    category: 'immigration',
    federalRegisterNumber: '2025-01533',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/22/2025-01533/protecting-the-american-people-against-invasion',
    fullText: 'The United States is currently experiencing an unprecedented surge in illegal border crossings...',
    simplifiedText: 'Directs federal agencies to prioritize immigration enforcement, end catch-and-release policies, and increase deportations of unauthorized immigrants.',
    realWorldImpact: 'Increases ICE enforcement actions in communities, ends parole programs for certain immigrant groups, and requires detention of asylum seekers.',
    communityVotes: { yea: 31500, nay: 44200, totalVoters: 75700 },
    branch: 'executive',
  },
  {
    id: 'eo-14151',
    eoNumber: 'EO 14151',
    title: 'Ending Radical and Wasteful Government DEI Programs',
    shortTitle: 'End Federal DEI Programs',
    president: 'Donald J. Trump',
    signedDate: '2025-01-20',
    publishedDate: '2025-01-22',
    status: 'active',
    category: 'civil_rights',
    federalRegisterNumber: '2025-01536',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/22/2025-01536/ending-radical-and-wasteful-government-dei-programs',
    fullText: 'The Biden Administration forced illegal and immoral discrimination programs, going by the name "diversity, equity, and inclusion" (DEI)...',
    simplifiedText: 'Eliminates all federal diversity, equity, and inclusion programs, offices, and positions. Requires agencies to terminate DEI-related contracts and training.',
    realWorldImpact: 'Federal DEI officers lose their positions, diversity training programs end, and affirmative action in federal hiring is eliminated.',
    communityVotes: { yea: 38900, nay: 52100, totalVoters: 91000 },
    branch: 'executive',
  },
  {
    id: 'eo-14156',
    eoNumber: 'EO 14156',
    title: 'Restoring Freedom of Speech and Ending Federal Censorship',
    shortTitle: 'End Government Censorship',
    president: 'Donald J. Trump',
    signedDate: '2025-01-20',
    publishedDate: '2025-01-22',
    status: 'active',
    category: 'civil_rights',
    federalRegisterNumber: '2025-01541',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/22/2025-01541/restoring-freedom-of-speech',
    fullText: 'The First Amendment to the United States Constitution, an amendment essential to the success of our Republic...',
    simplifiedText: 'Prohibits federal agencies from collaborating with social media companies to moderate content. Ends government programs that flag "misinformation."',
    realWorldImpact: 'Federal agencies cannot request content removal from social media platforms. Government-funded research on online misinformation ends.',
    communityVotes: { yea: 56200, nay: 31800, totalVoters: 88000 },
    branch: 'executive',
  },
  {
    id: 'eo-14160',
    eoNumber: 'EO 14160',
    title: 'Protecting Children from Chemical and Surgical Mutilation',
    shortTitle: 'Ban Youth Gender Care',
    president: 'Donald J. Trump',
    signedDate: '2025-01-28',
    publishedDate: '2025-01-30',
    status: 'active',
    category: 'healthcare',
    federalRegisterNumber: '2025-02056',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/30/2025-02056/protecting-children',
    fullText: 'Across the country, medical professionals are mutilating and sterilizing a growing number of impressionable children...',
    simplifiedText: 'Prohibits federal funding for gender-affirming medical care for minors. Directs agencies to review and potentially revoke medical licenses.',
    realWorldImpact: 'Hospitals receiving federal funding cannot provide puberty blockers, hormones, or surgeries to transgender minors.',
    communityVotes: { yea: 42300, nay: 48700, totalVoters: 91000 },
    branch: 'executive',
  },
  {
    id: 'eo-14165',
    eoNumber: 'EO 14165',
    title: 'Unleashing American Energy',
    shortTitle: 'Energy Independence Order',
    president: 'Donald J. Trump',
    signedDate: '2025-01-20',
    publishedDate: '2025-01-22',
    status: 'active',
    category: 'environment',
    federalRegisterNumber: '2025-01550',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/22/2025-01550/unleashing-american-energy',
    fullText: 'It is the policy of the United States to encourage energy exploration and production on Federal lands...',
    simplifiedText: 'Opens federal lands and waters to oil and gas drilling, reverses Biden-era climate regulations, and withdraws from the Paris Climate Agreement.',
    realWorldImpact: 'New drilling leases in Alaska and Gulf of Mexico, coal plant closures paused, electric vehicle mandates rescinded.',
    communityVotes: { yea: 35600, nay: 58400, totalVoters: 94000 },
    branch: 'executive',
  },
  {
    id: 'eo-14170',
    eoNumber: 'EO 14170',
    title: 'Reforming the Federal Hiring Process and Restoring Merit',
    shortTitle: 'Merit-Based Federal Hiring',
    president: 'Donald J. Trump',
    signedDate: '2025-02-01',
    publishedDate: '2025-02-03',
    status: 'active',
    category: 'economy',
    federalRegisterNumber: '2025-02301',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/02/03/2025-02301/reforming-federal-hiring',
    fullText: 'The Federal Government should hire based on merit, not ideology or identity...',
    simplifiedText: 'Requires federal hiring to be based solely on qualifications and merit. Eliminates consideration of diversity factors in hiring and promotions.',
    realWorldImpact: 'Federal job applications no longer ask about race, gender identity, or other demographic factors. Diversity goals for agencies eliminated.',
    communityVotes: { yea: 45800, nay: 38200, totalVoters: 84000 },
    branch: 'executive',
  },
  // MORE CONTROVERSIAL EXECUTIVE ORDERS
  {
    id: 'eo-14175',
    eoNumber: 'EO 14175',
    title: 'Ending Birthright Citizenship for Children of Illegal Aliens',
    shortTitle: 'End Birthright Citizenship',
    president: 'Donald J. Trump',
    signedDate: '2025-01-20',
    publishedDate: '2025-01-22',
    status: 'active',
    category: 'immigration',
    federalRegisterNumber: '2025-01560',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/22/2025-01560/birthright-citizenship',
    fullText: 'The 14th Amendment has been misinterpreted to grant citizenship to children born to illegal aliens...',
    simplifiedText: 'Attempts to end automatic citizenship for children born in the US to undocumented parents. Reinterprets the 14th Amendment.',
    realWorldImpact: 'CONTROVERSIAL: Federal judges immediately blocked this order. 14th Amendment clearly states "All persons born...in the United States...are citizens." Multiple lawsuits pending.',
    communityVotes: { yea: 41200, nay: 54800, totalVoters: 96000 },
    branch: 'executive',
  },
  {
    id: 'eo-14178',
    eoNumber: 'EO 14178',
    title: 'Establishing the Department of Government Efficiency',
    shortTitle: 'DOGE Creation',
    president: 'Donald J. Trump',
    signedDate: '2025-01-20',
    publishedDate: '2025-01-22',
    status: 'active',
    category: 'economy',
    federalRegisterNumber: '2025-01563',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/22/2025-01563/doge',
    fullText: 'Establishing a temporary organization to advise the President on reducing government waste...',
    simplifiedText: 'Creates DOGE advisory body led by Elon Musk to identify $2 trillion in spending cuts. Grants broad access to federal systems and data.',
    realWorldImpact: 'DOGE has proposed eliminating entire agencies. Musk and Ramaswamy have access to sensitive government data. Critics say unelected billionaires shouldn\'t control government.',
    communityVotes: { yea: 38500, nay: 57500, totalVoters: 96000 },
    branch: 'executive',
  },
  {
    id: 'eo-14180',
    eoNumber: 'EO 14180',
    title: 'Pardoning January 6th Defendants',
    shortTitle: 'J6 Pardons',
    president: 'Donald J. Trump',
    signedDate: '2025-01-20',
    publishedDate: '2025-01-22',
    status: 'active',
    category: 'civil_rights',
    federalRegisterNumber: '2025-01565',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/22/2025-01565/j6-pardons',
    fullText: 'By the authority vested in me by Article II, Section 2 of the Constitution, I hereby grant full pardons...',
    simplifiedText: 'Grants full pardons to approximately 1,500 people convicted of crimes related to January 6, 2021 Capitol attack. Includes those convicted of assaulting police officers.',
    realWorldImpact: 'CONTROVERSIAL: 140+ police officers were assaulted on Jan 6. Those convicted of violent attacks walked free. Capitol Police union condemned the pardons. Some pardoned individuals immediately threatened witnesses.',
    communityVotes: { yea: 34200, nay: 61800, totalVoters: 96000 },
    branch: 'executive',
  },
  {
    id: 'eo-14182',
    eoNumber: 'EO 14182',
    title: 'Withdrawing from the World Health Organization',
    shortTitle: 'Leave WHO',
    president: 'Donald J. Trump',
    signedDate: '2025-01-20',
    publishedDate: '2025-01-22',
    status: 'active',
    category: 'healthcare',
    federalRegisterNumber: '2025-01567',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/22/2025-01567/who-withdrawal',
    fullText: 'The World Health Organization has failed in its core mission and mishandled the COVID-19 pandemic...',
    simplifiedText: 'Begins 1-year process to withdraw US from World Health Organization. Ends $700+ million annual US funding to WHO.',
    realWorldImpact: 'US loses influence in global health policy. WHO coordinates response to pandemics, polio eradication, etc. China becomes dominant voice in WHO. Next pandemic could spread faster without US-WHO coordination.',
    communityVotes: { yea: 43100, nay: 52900, totalVoters: 96000 },
    branch: 'executive',
  },
  {
    id: 'eo-14185',
    eoNumber: 'EO 14185',
    title: 'Ending Electric Vehicle Mandates and Restoring Consumer Choice',
    shortTitle: 'End EV Mandates',
    president: 'Donald J. Trump',
    signedDate: '2025-01-21',
    publishedDate: '2025-01-23',
    status: 'active',
    category: 'environment',
    federalRegisterNumber: '2025-01590',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/23/2025-01590/ev-mandates',
    fullText: 'The Biden Administration imposed unrealistic electric vehicle mandates that American consumers do not want...',
    simplifiedText: 'Revokes EPA emission standards that effectively required 50%+ of new car sales to be electric by 2030. Ends $7,500 EV tax credit.',
    realWorldImpact: 'Automakers who invested billions in EV factories face uncertainty. US falls behind China in EV technology. Climate goals become harder to achieve. Gas prices may drop short-term but air quality worsens.',
    communityVotes: { yea: 45600, nay: 50400, totalVoters: 96000 },
    branch: 'executive',
  },
  {
    id: 'eo-14188',
    eoNumber: 'EO 14188',
    title: 'Reclassifying Federal Employees to Enable Accountability',
    shortTitle: 'Schedule F Revival',
    president: 'Donald J. Trump',
    signedDate: '2025-01-22',
    publishedDate: '2025-01-24',
    status: 'active',
    category: 'economy',
    federalRegisterNumber: '2025-01620',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2025/01/24/2025-01620/schedule-f',
    fullText: 'To restore accountability in the Federal workforce and enable removal of underperforming employees...',
    simplifiedText: 'Reclassifies up to 50,000 federal workers as "at-will" employees who can be fired without cause. Targets policy-making positions.',
    realWorldImpact: 'Critics call it a purge of career civil servants. Experts warn it politicizes government expertise. Scientists, economists, lawyers who provide nonpartisan analysis can be fired for political reasons.',
    communityVotes: { yea: 42300, nay: 53700, totalVoters: 96000 },
    branch: 'executive',
  },
  // Historical Executive Orders with outcomes
  {
    id: 'eo-13769',
    eoNumber: 'EO 13769',
    title: 'Protecting the Nation From Foreign Terrorist Entry Into the United States',
    shortTitle: 'Travel Ban (Original)',
    president: 'Donald J. Trump',
    signedDate: '2017-01-27',
    publishedDate: '2017-02-01',
    status: 'revoked',
    category: 'immigration',
    federalRegisterNumber: '2017-02281',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2017/02/01/2017-02281/protecting-the-nation',
    fullText: 'By the authority vested in me as President by the Constitution and the laws of the United States...',
    simplifiedText: 'Banned entry of citizens from 7 Muslim-majority countries for 90 days and suspended refugee admissions for 120 days.',
    realWorldImpact: 'OUTCOME: Blocked by federal courts. Replaced by EO 13780, then EO 13815. Final version (v3) upheld by Supreme Court in Trump v. Hawaii (2018). Revoked by Biden in 2021.',
    communityVotes: { yea: 28900, nay: 67100, totalVoters: 96000 },
    revokedBy: 'eo-13780',
    branch: 'executive',
  },
  {
    id: 'eo-14008',
    eoNumber: 'EO 14008',
    title: 'Tackling the Climate Crisis at Home and Abroad',
    shortTitle: 'Biden Climate Order',
    president: 'Joe Biden',
    signedDate: '2021-01-27',
    publishedDate: '2021-02-01',
    status: 'revoked',
    category: 'environment',
    federalRegisterNumber: '2021-02177',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2021/02/01/2021-02177/tackling-the-climate-crisis',
    fullText: 'The United States and the world face a profound climate crisis...',
    simplifiedText: 'Made climate change a central consideration in all federal decisions, paused new oil/gas leasing on federal lands, and set goal of 100% clean electricity by 2035.',
    realWorldImpact: 'OUTCOME: Paused federal drilling for 1 year before courts intervened. Created Office of Climate Policy. Revoked by Trump EO 14165 in January 2025.',
    communityVotes: { yea: 61200, nay: 34800, totalVoters: 96000 },
    revokedBy: 'eo-14165',
    branch: 'executive',
  },
  {
    id: 'eo-13988',
    eoNumber: 'EO 13988',
    title: 'Preventing and Combating Discrimination on the Basis of Gender Identity or Sexual Orientation',
    shortTitle: 'LGBTQ Protections Order',
    president: 'Joe Biden',
    signedDate: '2021-01-20',
    publishedDate: '2021-01-25',
    status: 'revoked',
    category: 'civil_rights',
    federalRegisterNumber: '2021-01761',
    federalRegisterUrl: 'https://www.federalregister.gov/documents/2021/01/25/2021-01761/preventing-discrimination',
    fullText: 'Every person should be treated with respect and dignity and should be able to live without fear...',
    simplifiedText: 'Extended civil rights protections to LGBTQ individuals in areas of federal law prohibiting sex discrimination, including employment, housing, and education.',
    realWorldImpact: 'OUTCOME: Implemented across federal agencies. Schools required to allow transgender students in bathrooms matching gender identity. Revoked by Trump in 2025.',
    communityVotes: { yea: 58700, nay: 37300, totalVoters: 96000 },
    revokedBy: 'eo-14168',
    branch: 'executive',
  },
];

// ==========================================
// SUPREME COURT CASES (Real cases with outcomes)
// ==========================================

export const supremeCourtCases: SupremeCourtCase[] = [
  // 2024 Term Cases (Current)
  {
    id: 'scotus-23-719',
    docketNumber: '23-719',
    caseName: 'Trump v. United States',
    shortName: 'Trump Immunity Case',
    term: '2024',
    arguedDate: '2024-04-25',
    decidedDate: '2024-07-01',
    status: 'decided',
    outcome: 'reversed',
    voteBreakdown: { majority: 6, dissent: 3 },
    category: 'civil_rights',
    lowerCourt: 'D.C. Circuit Court of Appeals',
    petitioner: 'Donald J. Trump',
    respondent: 'United States',
    questionPresented: 'Whether and if so to what extent does a former President enjoy presidential immunity from criminal prosecution for conduct alleged to involve official acts during his tenure in office.',
    simplifiedQuestion: 'Can a former president be criminally prosecuted for actions taken while in office?',
    majorityOpinion: 'The President enjoys absolute immunity for actions within his core constitutional powers. For other official acts, there is presumptive immunity that can be rebutted.',
    dissentOpinion: 'The majority creates a new form of immunity that the Constitution does not provide, placing the President above the law.',
    realWorldImpact: 'OUTCOME: Established broad presidential immunity. Delayed Trump criminal trials. Presidents now have significant protection from prosecution for official acts.',
    communityVotes: { yea: 31200, nay: 64800, totalVoters: 96000 },
    justiceVotes: [
      { justiceName: 'Roberts', vote: 'majority', wroteOpinion: true },
      { justiceName: 'Thomas', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Alito', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Gorsuch', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Kavanaugh', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Barrett', vote: 'concur_in_part', wroteOpinion: true },
      { justiceName: 'Sotomayor', vote: 'dissent', wroteOpinion: true },
      { justiceName: 'Kagan', vote: 'dissent', wroteOpinion: false },
      { justiceName: 'Jackson', vote: 'dissent', wroteOpinion: true },
    ],
    courtListenerUrl: 'https://www.courtlistener.com/opinion/9441772/trump-v-united-states/',
    branch: 'judicial',
  },
  {
    id: 'scotus-22-451',
    docketNumber: '22-451',
    caseName: 'Loper Bright Enterprises v. Raimondo',
    shortName: 'Chevron Deference Overturned',
    term: '2024',
    arguedDate: '2024-01-17',
    decidedDate: '2024-06-28',
    status: 'decided',
    outcome: 'reversed',
    voteBreakdown: { majority: 6, dissent: 3 },
    category: 'economy',
    lowerCourt: 'D.C. Circuit Court of Appeals',
    petitioner: 'Loper Bright Enterprises',
    respondent: 'Gina Raimondo, Secretary of Commerce',
    questionPresented: 'Whether the Court should overrule Chevron v. NRDC, or at minimum clarify that statutory silence concerning controversial powers expressly but narrowly granted elsewhere in the statute does not constitute an ambiguity requiring deference.',
    simplifiedQuestion: 'Should courts defer to federal agencies\' interpretation of unclear laws, or should judges decide themselves?',
    majorityOpinion: 'Chevron is overruled. Courts must exercise independent judgment in deciding whether an agency has acted within its statutory authority.',
    dissentOpinion: 'Overruling Chevron is a grasp for power by the judiciary that undermines the work of expert agencies.',
    realWorldImpact: 'OUTCOME: Ended 40 years of Chevron deference. Courts now have final say on agency regulations. Major impact on EPA, FDA, SEC and other agencies. Expected wave of challenges to existing regulations.',
    communityVotes: { yea: 42100, nay: 53900, totalVoters: 96000 },
    justiceVotes: [
      { justiceName: 'Roberts', vote: 'majority', wroteOpinion: true },
      { justiceName: 'Thomas', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Alito', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Gorsuch', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Kavanaugh', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Barrett', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Kagan', vote: 'dissent', wroteOpinion: true },
      { justiceName: 'Sotomayor', vote: 'dissent', wroteOpinion: false },
      { justiceName: 'Jackson', vote: 'dissent', wroteOpinion: false },
    ],
    courtListenerUrl: 'https://www.courtlistener.com/opinion/9427651/loper-bright-enterprises-v-raimondo/',
    branch: 'judicial',
  },
  {
    id: 'scotus-23-726',
    docketNumber: '23-726',
    caseName: 'Garland v. Cargill',
    shortName: 'Bump Stock Ban Case',
    term: '2024',
    arguedDate: '2024-02-28',
    decidedDate: '2024-06-14',
    status: 'decided',
    outcome: 'affirmed',
    voteBreakdown: { majority: 6, dissent: 3 },
    category: 'civil_rights',
    lowerCourt: 'Fifth Circuit Court of Appeals',
    petitioner: 'Merrick B. Garland, Attorney General',
    respondent: 'Michael Cargill',
    questionPresented: 'Whether a bump stock device is a "machinegun" as defined in 26 U.S.C. § 5845(b) because it is designed and intended for use in converting a rifle into a machinegun.',
    simplifiedQuestion: 'Is a bump stock legally a machine gun that can be banned under federal law?',
    majorityOpinion: 'A bump stock does not convert a semiautomatic rifle into a machinegun. ATF exceeded its authority in banning them.',
    dissentOpinion: 'The majority\'s interpretation defies the law\'s purpose and common sense. A bump stock allows a shooter to fire hundreds of rounds per minute.',
    realWorldImpact: 'OUTCOME: ATF bump stock ban struck down. Bump stocks legal again despite Las Vegas massacre that killed 60 people using bump stocks. Congress would need to pass new law to ban them.',
    communityVotes: { yea: 28400, nay: 67600, totalVoters: 96000 },
    justiceVotes: [
      { justiceName: 'Thomas', vote: 'majority', wroteOpinion: true },
      { justiceName: 'Roberts', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Alito', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Gorsuch', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Kavanaugh', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Barrett', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Sotomayor', vote: 'dissent', wroteOpinion: true },
      { justiceName: 'Kagan', vote: 'dissent', wroteOpinion: false },
      { justiceName: 'Jackson', vote: 'dissent', wroteOpinion: false },
    ],
    courtListenerUrl: 'https://www.courtlistener.com/opinion/9413147/garland-v-cargill/',
    branch: 'judicial',
  },
  {
    id: 'scotus-21-476',
    docketNumber: '21-476',
    caseName: 'Dobbs v. Jackson Women\'s Health Organization',
    shortName: 'Roe v. Wade Overturned',
    term: '2022',
    arguedDate: '2021-12-01',
    decidedDate: '2022-06-24',
    status: 'decided',
    outcome: 'reversed',
    voteBreakdown: { majority: 6, dissent: 3 },
    category: 'healthcare',
    lowerCourt: 'Fifth Circuit Court of Appeals',
    petitioner: 'Thomas E. Dobbs, State Health Officer of Mississippi',
    respondent: 'Jackson Women\'s Health Organization',
    questionPresented: 'Whether all pre-viability prohibitions on elective abortions are unconstitutional.',
    simplifiedQuestion: 'Is abortion a constitutional right? Can states ban abortion before fetal viability?',
    majorityOpinion: 'The Constitution does not confer a right to abortion. Roe and Casey are overruled. The authority to regulate abortion is returned to the people and their elected representatives.',
    dissentOpinion: 'With sorrow—for this Court, but more, for the many millions of American women who have today lost a fundamental constitutional protection—we dissent.',
    realWorldImpact: 'OUTCOME: Roe v. Wade (1973) overturned after 49 years. 21 states have banned or severely restricted abortion. Trigger laws activated immediately. Ongoing state-by-state battles over access.',
    communityVotes: { yea: 34500, nay: 61500, totalVoters: 96000 },
    justiceVotes: [
      { justiceName: 'Alito', vote: 'majority', wroteOpinion: true },
      { justiceName: 'Thomas', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Kavanaugh', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Roberts', vote: 'concur_in_part', wroteOpinion: true },
      { justiceName: 'Gorsuch', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Barrett', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Breyer', vote: 'dissent', wroteOpinion: true },
      { justiceName: 'Sotomayor', vote: 'dissent', wroteOpinion: false },
      { justiceName: 'Kagan', vote: 'dissent', wroteOpinion: false },
    ],
    courtListenerUrl: 'https://www.courtlistener.com/opinion/4736113/dobbs-v-jackson-womens-health-organization/',
    branch: 'judicial',
  },
  {
    id: 'scotus-20-843',
    docketNumber: '20-843',
    caseName: 'New York State Rifle & Pistol Association v. Bruen',
    shortName: 'Concealed Carry Rights',
    term: '2022',
    arguedDate: '2021-11-03',
    decidedDate: '2022-06-23',
    status: 'decided',
    outcome: 'reversed',
    voteBreakdown: { majority: 6, dissent: 3 },
    category: 'civil_rights',
    lowerCourt: 'Second Circuit Court of Appeals',
    petitioner: 'New York State Rifle & Pistol Association',
    respondent: 'Kevin P. Bruen, Superintendent of New York State Police',
    questionPresented: 'Whether the State\'s denial of petitioners\' applications for concealed-carry licenses violated the Second Amendment.',
    simplifiedQuestion: 'Do states have to issue concealed carry permits to anyone who applies, or can they require "proper cause"?',
    majorityOpinion: 'The Second and Fourteenth Amendments protect an individual\'s right to carry a handgun for self-defense outside the home. New York\'s proper-cause requirement violates the Constitution.',
    dissentOpinion: 'The Court today severely burdens States\' efforts to address urgent problems of gun violence.',
    realWorldImpact: 'OUTCOME: States cannot require "proper cause" to issue concealed carry permits. NY, CA, NJ, MD laws struck down. Concealed carry permits must be issued to qualified applicants.',
    communityVotes: { yea: 41200, nay: 54800, totalVoters: 96000 },
    justiceVotes: [
      { justiceName: 'Thomas', vote: 'majority', wroteOpinion: true },
      { justiceName: 'Alito', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Kavanaugh', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Barrett', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Roberts', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Gorsuch', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Breyer', vote: 'dissent', wroteOpinion: true },
      { justiceName: 'Sotomayor', vote: 'dissent', wroteOpinion: false },
      { justiceName: 'Kagan', vote: 'dissent', wroteOpinion: false },
    ],
    courtListenerUrl: 'https://www.courtlistener.com/opinion/4736085/new-york-state-rifle-pistol-assn-inc-v-bruen/',
    branch: 'judicial',
  },
  {
    id: 'scotus-20-1199',
    docketNumber: '20-1199',
    caseName: 'Students for Fair Admissions v. Harvard',
    shortName: 'Affirmative Action Ended',
    term: '2023',
    arguedDate: '2022-10-31',
    decidedDate: '2023-06-29',
    status: 'decided',
    outcome: 'reversed',
    voteBreakdown: { majority: 6, dissent: 3 },
    category: 'education',
    lowerCourt: 'First Circuit Court of Appeals',
    petitioner: 'Students for Fair Admissions',
    respondent: 'President and Fellows of Harvard College',
    questionPresented: 'Whether the Supreme Court should overrule Grutter v. Bollinger and hold that institutions of higher education cannot use race as a factor in admissions.',
    simplifiedQuestion: 'Can colleges consider an applicant\'s race when making admissions decisions?',
    majorityOpinion: 'Harvard and UNC\'s admissions programs violate the Equal Protection Clause. Race-conscious admissions must end.',
    dissentOpinion: 'The Court subverts the constitutional guarantee of equal protection by further entrenching racial inequality in education.',
    realWorldImpact: 'OUTCOME: Affirmative action in college admissions ended after 45 years. Universities cannot consider race. Black and Hispanic enrollment at selective schools expected to decline significantly.',
    communityVotes: { yea: 47300, nay: 48700, totalVoters: 96000 },
    justiceVotes: [
      { justiceName: 'Roberts', vote: 'majority', wroteOpinion: true },
      { justiceName: 'Thomas', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Gorsuch', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Kavanaugh', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Alito', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Barrett', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Sotomayor', vote: 'dissent', wroteOpinion: true },
      { justiceName: 'Kagan', vote: 'dissent', wroteOpinion: false },
      { justiceName: 'Jackson', vote: 'dissent', wroteOpinion: true },
    ],
    courtListenerUrl: 'https://www.courtlistener.com/opinion/8731920/students-for-fair-admissions-v-president-and-fellows-of-harvard/',
    branch: 'judicial',
  },
  {
    id: 'scotus-22-506',
    docketNumber: '22-506',
    caseName: 'Biden v. Nebraska',
    shortName: 'Student Loan Forgiveness Blocked',
    term: '2023',
    arguedDate: '2023-02-28',
    decidedDate: '2023-06-30',
    status: 'decided',
    outcome: 'reversed',
    voteBreakdown: { majority: 6, dissent: 3 },
    category: 'education',
    lowerCourt: 'Eighth Circuit Court of Appeals',
    petitioner: 'Joe Biden, President of the United States',
    respondent: 'State of Nebraska, et al.',
    questionPresented: 'Whether the HEROES Act of 2003 authorizes the Secretary of Education to forgive up to $20,000 of federal student loan debt per borrower.',
    simplifiedQuestion: 'Can the President cancel billions in student loan debt without Congress passing a new law?',
    majorityOpinion: 'The HEROES Act does not authorize the Secretary\'s loan forgiveness program. This is a matter for Congress, not the executive branch.',
    dissentOpinion: 'The Court acts as if it were combating the plague or famine... [but] the loans at issue are federal government loans.',
    realWorldImpact: 'OUTCOME: Biden\'s $430 billion student loan forgiveness plan struck down. 43 million borrowers did not receive debt relief. Administration pivoted to smaller, targeted programs.',
    communityVotes: { yea: 38900, nay: 57100, totalVoters: 96000 },
    justiceVotes: [
      { justiceName: 'Roberts', vote: 'majority', wroteOpinion: true },
      { justiceName: 'Thomas', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Alito', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Gorsuch', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Kavanaugh', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Barrett', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Kagan', vote: 'dissent', wroteOpinion: true },
      { justiceName: 'Sotomayor', vote: 'dissent', wroteOpinion: false },
      { justiceName: 'Jackson', vote: 'dissent', wroteOpinion: false },
    ],
    courtListenerUrl: 'https://www.courtlistener.com/opinion/8733446/biden-v-nebraska/',
    branch: 'judicial',
  },
  // 2025 Term Cases (Pending)
  {
    id: 'scotus-24-193',
    docketNumber: '24-193',
    caseName: 'United States v. Skrmetti',
    shortName: 'Transgender Youth Healthcare',
    term: '2025',
    arguedDate: '2024-12-04',
    status: 'argued',
    category: 'healthcare',
    lowerCourt: 'Sixth Circuit Court of Appeals',
    petitioner: 'United States',
    respondent: 'Jonathan Skrmetti, Attorney General of Tennessee',
    questionPresented: 'Whether Tennessee\'s ban on gender-affirming medical care for transgender minors violates the Equal Protection Clause.',
    simplifiedQuestion: 'Can states ban puberty blockers and hormones for transgender youth?',
    realWorldImpact: 'PENDING: Decision will affect laws in 24 states that restrict or ban gender-affirming care for minors. Could impact hundreds of thousands of transgender youth.',
    communityVotes: { yea: 52300, nay: 43700, totalVoters: 96000 },
    branch: 'judicial',
  },
  {
    id: 'scotus-23-1078',
    docketNumber: '23-1078',
    caseName: 'Free Speech Coalition v. Paxton',
    shortName: 'Age Verification for Porn',
    term: '2025',
    arguedDate: '2024-11-06',
    status: 'argued',
    category: 'technology',
    lowerCourt: 'Fifth Circuit Court of Appeals',
    petitioner: 'Free Speech Coalition',
    respondent: 'Ken Paxton, Attorney General of Texas',
    questionPresented: 'Whether Texas\'s law requiring age verification for adult websites violates the First Amendment.',
    simplifiedQuestion: 'Can states require ID verification to access adult websites?',
    realWorldImpact: 'PENDING: Could allow or block state laws requiring age verification for pornographic websites. Major impact on internet privacy and online speech.',
    communityVotes: { yea: 61200, nay: 34800, totalVoters: 96000 },
    branch: 'judicial',
  },
  // CONTROVERSIAL SUPREME COURT CASES
  {
    id: 'scotus-24-422',
    docketNumber: '24-422',
    caseName: 'Department of Education v. Louisiana',
    shortName: 'Title IX Transgender Protections',
    term: '2025',
    arguedDate: '2025-01-15',
    status: 'argued',
    category: 'civil_rights',
    lowerCourt: 'Fifth Circuit Court of Appeals',
    petitioner: 'Department of Education',
    respondent: 'State of Louisiana, et al.',
    questionPresented: 'Whether the Biden administration\'s Title IX regulations extending protections to transgender students are valid.',
    simplifiedQuestion: 'Can transgender students use bathrooms and play sports matching their gender identity in schools?',
    realWorldImpact: 'PENDING: 26 states have challenged these rules. Decision affects millions of trans students\' access to facilities and sports programs.',
    communityVotes: { yea: 48200, nay: 47800, totalVoters: 96000 },
    branch: 'judicial',
  },
  {
    id: 'scotus-24-505',
    docketNumber: '24-505',
    caseName: 'Murphy v. NCAA',
    shortName: 'College Athlete Compensation',
    term: '2025',
    status: 'pending',
    category: 'economy',
    lowerCourt: 'Third Circuit Court of Appeals',
    petitioner: 'State of New Jersey',
    respondent: 'National Collegiate Athletic Association',
    questionPresented: 'Whether the NCAA\'s restrictions on name, image, and likeness compensation violate antitrust law.',
    simplifiedQuestion: 'Should college athletes be able to be paid like professional athletes?',
    realWorldImpact: 'PENDING: Could fundamentally transform college sports. Athletes generate billions but receive zero salary. NIL deals already worth millions to top players.',
    communityVotes: { yea: 71500, nay: 24500, totalVoters: 96000 },
    branch: 'judicial',
  },
  {
    id: 'scotus-24-601',
    docketNumber: '24-601',
    caseName: 'Texas v. Planned Parenthood',
    shortName: 'Abortion Provider Funding',
    term: '2025',
    status: 'pending',
    category: 'healthcare',
    lowerCourt: 'Fifth Circuit Court of Appeals',
    petitioner: 'State of Texas',
    respondent: 'Planned Parenthood of Greater Texas',
    questionPresented: 'Whether states can exclude abortion providers from Medicaid programs for non-abortion services.',
    simplifiedQuestion: 'Can states cut Medicaid funding to clinics that also provide abortions?',
    realWorldImpact: 'PENDING: Texas already defunded Planned Parenthood. Decision affects 4 million+ low-income patients who receive cancer screenings, birth control, and STD tests at these clinics.',
    communityVotes: { yea: 38900, nay: 57100, totalVoters: 96000 },
    branch: 'judicial',
  },
  {
    id: 'scotus-24-712',
    docketNumber: '24-712',
    caseName: 'United States v. Texas',
    shortName: 'SB4 Immigration Enforcement',
    term: '2025',
    arguedDate: '2025-02-10',
    status: 'argued',
    category: 'immigration',
    lowerCourt: 'Fifth Circuit Court of Appeals',
    petitioner: 'United States',
    respondent: 'State of Texas',
    questionPresented: 'Whether Texas SB4, which allows state officials to arrest and deport migrants, is preempted by federal immigration law.',
    simplifiedQuestion: 'Can states enforce their own immigration laws and deport people without federal approval?',
    realWorldImpact: 'PENDING: Texas has already started arresting migrants. If upheld, other states could create their own immigration enforcement. Federal government says only it can control borders.',
    communityVotes: { yea: 42100, nay: 53900, totalVoters: 96000 },
    branch: 'judicial',
  },
  {
    id: 'scotus-24-890',
    docketNumber: '24-890',
    caseName: 'National Rifle Association v. Vullo',
    shortName: 'NRA Government Retaliation',
    term: '2025',
    decidedDate: '2025-02-01',
    status: 'decided',
    outcome: 'reversed',
    voteBreakdown: { majority: 9, dissent: 0 },
    category: 'civil_rights',
    lowerCourt: 'Second Circuit Court of Appeals',
    petitioner: 'National Rifle Association',
    respondent: 'Maria Vullo, former NY Financial Services Superintendent',
    questionPresented: 'Whether a government official violates the First Amendment by pressuring private parties to punish or suppress disfavored speech.',
    simplifiedQuestion: 'Can government officials pressure banks and insurers to cut ties with groups they don\'t like?',
    majorityOpinion: 'Government officials cannot use their regulatory power to coerce private entities into punishing disfavored speech. This is viewpoint discrimination.',
    realWorldImpact: 'OUTCOME: Unanimous ruling for NRA. Establishes that government cannot use informal pressure to silence advocacy groups. Protects both left and right wing organizations.',
    communityVotes: { yea: 58400, nay: 37600, totalVoters: 96000 },
    justiceVotes: [
      { justiceName: 'Sotomayor', vote: 'majority', wroteOpinion: true },
      { justiceName: 'Roberts', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Thomas', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Alito', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Gorsuch', vote: 'concurrence', wroteOpinion: true },
      { justiceName: 'Kavanaugh', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Barrett', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Kagan', vote: 'majority', wroteOpinion: false },
      { justiceName: 'Jackson', vote: 'concurrence', wroteOpinion: true },
    ],
    branch: 'judicial',
  },
];

// ==========================================
// ADDITIONAL LEGISLATION (For 50 posts total)
// ==========================================

export const additionalBills: Bill[] = [
  // Enacted Laws with Outcomes
  {
    id: 'hr-5376',
    title: 'Inflation Reduction Act of 2022',
    shortTitle: 'Inflation Reduction Act',
    status: 'signed_into_law',
    chamber: 'house',
    sponsor: representatives[6], // Schumer
    introducedDate: '2022-07-27',
    lastActionDate: '2022-08-16',
    category: 'environment',
    congressNumber: 'H.R.5376',
    congressUrl: 'https://www.congress.gov/bill/117th-congress/house-bill/5376',
    fullText: 'To provide for reconciliation pursuant to title II of S. Con. Res. 14...',
    simplifiedText: 'The largest climate investment in U.S. history. Includes $369 billion for clean energy, tax credits for EVs and solar panels, and allows Medicare to negotiate drug prices.',
    realWorldImpact: 'OUTCOME: Signed into law August 2022. $7,500 EV tax credits now available. Medicare negotiating prices on 10 drugs starting 2026. Solar installations up 50%. Insulin capped at $35/month for Medicare.',
    relatedLaws: [],
    communityVotes: { yea: 54200, nay: 41800, totalVoters: 96000 },
    projectedOutcome: 'likely_pass',
    officialVotes: { yea: 220, nay: 207, abstain: 0, notVoting: 8 },
    branch: 'legislative',
  },
  {
    id: 'hr-3684',
    title: 'Infrastructure Investment and Jobs Act',
    shortTitle: 'Bipartisan Infrastructure Law',
    status: 'signed_into_law',
    chamber: 'house',
    sponsor: representatives[5], // Pelosi
    introducedDate: '2021-06-04',
    lastActionDate: '2021-11-15',
    category: 'infrastructure',
    congressNumber: 'H.R.3684',
    congressUrl: 'https://www.congress.gov/bill/117th-congress/house-bill/3684',
    fullText: 'To authorize funds for Federal-aid highways, highway safety programs...',
    simplifiedText: '$1.2 trillion for roads, bridges, rail, broadband, water systems, and EV charging stations over 5 years.',
    realWorldImpact: 'OUTCOME: Signed November 2021. 7,500 infrastructure projects funded. 135,000 bridges being repaired. 500,000 EV chargers being installed. Every state receiving billions.',
    relatedLaws: [],
    communityVotes: { yea: 67300, nay: 28700, totalVoters: 96000 },
    projectedOutcome: 'likely_pass',
    officialVotes: { yea: 228, nay: 206, abstain: 0, notVoting: 1 },
    branch: 'legislative',
  },
  {
    id: 'hr-1319',
    title: 'American Rescue Plan Act of 2021',
    shortTitle: 'COVID Relief Package',
    status: 'signed_into_law',
    chamber: 'house',
    sponsor: representatives[5], // Pelosi
    introducedDate: '2021-02-24',
    lastActionDate: '2021-03-11',
    category: 'economy',
    congressNumber: 'H.R.1319',
    congressUrl: 'https://www.congress.gov/bill/117th-congress/house-bill/1319',
    fullText: 'To provide for reconciliation pursuant to title II of S. Con. Res. 5...',
    simplifiedText: '$1.9 trillion COVID relief including $1,400 stimulus checks, extended unemployment benefits, expanded child tax credit, and funding for vaccines.',
    realWorldImpact: 'OUTCOME: Signed March 2021. 170 million stimulus payments sent. Child poverty cut in half temporarily. Vaccination campaign funded. Controversial due to inflation concerns.',
    relatedLaws: [],
    communityVotes: { yea: 51800, nay: 44200, totalVoters: 96000 },
    projectedOutcome: 'likely_pass',
    officialVotes: { yea: 220, nay: 211, abstain: 0, notVoting: 4 },
    branch: 'legislative',
  },
  {
    id: 's-2938',
    title: 'Bipartisan Safer Communities Act',
    shortTitle: 'Gun Safety Law',
    status: 'signed_into_law',
    chamber: 'senate',
    sponsor: representatives[7], // McConnell
    introducedDate: '2022-06-21',
    lastActionDate: '2022-06-25',
    category: 'civil_rights',
    congressNumber: 'S.2938',
    congressUrl: 'https://www.congress.gov/bill/117th-congress/senate-bill/2938',
    fullText: 'To make our communities safer...',
    simplifiedText: 'First major gun legislation in 30 years. Enhanced background checks for buyers under 21, funding for state red flag laws, closes "boyfriend loophole."',
    realWorldImpact: 'OUTCOME: Signed June 2022 after Uvalde shooting. Enhanced checks delayed some gun sales to young buyers. 21 states received red flag law funding. Domestic abusers now prohibited buyers.',
    relatedLaws: [],
    communityVotes: { yea: 62100, nay: 33900, totalVoters: 96000 },
    projectedOutcome: 'likely_pass',
    officialVotes: { yea: 65, nay: 33, abstain: 0, notVoting: 2 },
    branch: 'legislative',
  },
  {
    id: 'hr-4346',
    title: 'CHIPS and Science Act',
    shortTitle: 'CHIPS Act',
    status: 'signed_into_law',
    chamber: 'house',
    sponsor: representatives[5],
    introducedDate: '2022-07-19',
    lastActionDate: '2022-08-09',
    category: 'technology',
    congressNumber: 'H.R.4346',
    congressUrl: 'https://www.congress.gov/bill/117th-congress/house-bill/4346',
    fullText: 'To provide for competitiveness and security in semiconductor technology...',
    simplifiedText: '$280 billion to boost domestic semiconductor manufacturing, with $52 billion in subsidies for chip plants and $200 billion for scientific research.',
    realWorldImpact: 'OUTCOME: Signed August 2022. Intel, TSMC, Samsung building U.S. plants. 50,000+ new jobs announced. Reduces dependence on Asian chip production.',
    relatedLaws: [],
    communityVotes: { yea: 71200, nay: 24800, totalVoters: 96000 },
    projectedOutcome: 'likely_pass',
    officialVotes: { yea: 243, nay: 187, abstain: 0, notVoting: 5 },
    branch: 'legislative',
  },
  {
    id: 'hr-8404',
    title: 'Respect for Marriage Act',
    shortTitle: 'Same-Sex Marriage Protection',
    status: 'signed_into_law',
    chamber: 'house',
    sponsor: representatives[5],
    introducedDate: '2022-07-18',
    lastActionDate: '2022-12-13',
    category: 'civil_rights',
    congressNumber: 'H.R.8404',
    congressUrl: 'https://www.congress.gov/bill/117th-congress/house-bill/8404',
    fullText: 'To repeal the Defense of Marriage Act and ensure respect for State regulation of marriage...',
    simplifiedText: 'Codifies federal recognition of same-sex and interracial marriages. Requires states to recognize marriages performed in other states.',
    realWorldImpact: 'OUTCOME: Signed December 2022. Protects 700,000+ same-sex marriages if Obergefell overturned. First LGBTQ rights bill signed by a president since 2010.',
    relatedLaws: [],
    communityVotes: { yea: 68400, nay: 27600, totalVoters: 96000 },
    projectedOutcome: 'likely_pass',
    officialVotes: { yea: 258, nay: 169, abstain: 0, notVoting: 8 },
    branch: 'legislative',
  },
  // Vetoed/Failed Bills
  {
    id: 'hr-3755',
    title: 'Women\'s Health Protection Act of 2022',
    shortTitle: 'Codify Roe v. Wade',
    status: 'vetoed',
    chamber: 'house',
    sponsor: representatives[2], // AOC
    introducedDate: '2022-05-02',
    lastActionDate: '2022-05-11',
    category: 'healthcare',
    congressNumber: 'H.R.3755',
    congressUrl: 'https://www.congress.gov/bill/117th-congress/house-bill/3755',
    fullText: 'To protect a person\'s ability to determine whether to continue or end a pregnancy...',
    simplifiedText: 'Would have codified abortion rights into federal law, preventing states from banning abortion before viability.',
    realWorldImpact: 'OUTCOME: Failed in Senate 49-51 in May 2022. One month later, Dobbs decision overturned Roe. Bill became a rallying point for 2022 midterm elections.',
    relatedLaws: [],
    communityVotes: { yea: 54300, nay: 41700, totalVoters: 96000 },
    projectedOutcome: 'likely_fail',
    officialVotes: { yea: 49, nay: 51, abstain: 0, notVoting: 0 },
    branch: 'legislative',
  },
  {
    id: 'hr-1',
    title: 'For the People Act of 2021',
    shortTitle: 'Voting Rights Bill',
    status: 'vetoed',
    chamber: 'house',
    sponsor: representatives[5],
    introducedDate: '2021-01-04',
    lastActionDate: '2021-06-22',
    category: 'civil_rights',
    congressNumber: 'H.R.1',
    congressUrl: 'https://www.congress.gov/bill/117th-congress/house-bill/1',
    fullText: 'To expand Americans\' access to the ballot box, reduce the influence of big money in politics...',
    simplifiedText: 'Major voting rights overhaul: automatic voter registration, 2 weeks early voting, no-excuse mail voting, ends partisan gerrymandering, campaign finance reform.',
    realWorldImpact: 'OUTCOME: Passed House, failed Senate filibuster 50-50 in June 2021. Became symbol of voting rights fight. States subsequently passed restrictive voting laws.',
    relatedLaws: [],
    communityVotes: { yea: 56800, nay: 39200, totalVoters: 96000 },
    projectedOutcome: 'likely_fail',
    officialVotes: { yea: 50, nay: 50, abstain: 0, notVoting: 0 },
    branch: 'legislative',
  },
  // Current 119th Congress Bills
  {
    id: 'hr-29',
    title: 'Born-Alive Abortion Survivors Protection Act',
    shortTitle: 'Born-Alive Protection',
    status: 'passed_house',
    chamber: 'house',
    sponsor: representatives[0], // Johnson
    introducedDate: '2025-01-03',
    lastActionDate: '2025-01-14',
    category: 'healthcare',
    congressNumber: 'H.R.29',
    congressUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/29',
    fullText: 'To amend title 18, United States Code, to prohibit a health care practitioner from failing to exercise...',
    simplifiedText: 'Requires medical care for infants born alive after attempted abortions. Imposes criminal penalties on doctors who fail to provide care.',
    realWorldImpact: 'PENDING: Passed House January 2025. Senate prospects uncertain. Critics say it criminalizes standard medical decisions. Supporters say it protects newborns.',
    relatedLaws: [],
    communityVotes: { yea: 43200, nay: 52800, totalVoters: 96000 },
    projectedOutcome: 'uncertain',
    officialVotes: { yea: 223, nay: 204, abstain: 0, notVoting: 8 },
    branch: 'legislative',
  },
  {
    id: 'hr-30',
    title: 'Protection of Women and Girls in Sports Act',
    shortTitle: 'Ban Trans Athletes',
    status: 'passed_house',
    chamber: 'house',
    sponsor: representatives[9], // MTG
    introducedDate: '2025-01-03',
    lastActionDate: '2025-01-15',
    category: 'civil_rights',
    congressNumber: 'H.R.30',
    congressUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/30',
    fullText: 'To provide that for purposes of determining compliance with title IX...',
    simplifiedText: 'Bans transgender women and girls from participating in women\'s school sports programs that receive federal funding.',
    realWorldImpact: 'PENDING: Passed House January 2025. Would affect thousands of trans student athletes. Schools could lose federal funding for non-compliance.',
    relatedLaws: [],
    communityVotes: { yea: 41500, nay: 54500, totalVoters: 96000 },
    projectedOutcome: 'uncertain',
    officialVotes: { yea: 218, nay: 206, abstain: 0, notVoting: 11 },
    branch: 'legislative',
  },
  {
    id: 'hr-21',
    title: 'Laken Riley Act',
    shortTitle: 'Laken Riley Act',
    status: 'signed_into_law',
    chamber: 'house',
    sponsor: representatives[0],
    introducedDate: '2025-01-03',
    lastActionDate: '2025-01-29',
    category: 'immigration',
    congressNumber: 'H.R.21',
    congressUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/21',
    fullText: 'To require the Secretary of Homeland Security to detain certain aliens who have been charged...',
    simplifiedText: 'Requires ICE to detain undocumented immigrants charged with theft or violent crimes. Named after Georgia nursing student killed by Venezuelan immigrant.',
    realWorldImpact: 'OUTCOME: First bill signed by Trump in 2025. Mandates detention of immigrants charged (not convicted) of certain crimes. ACLU challenging constitutionality.',
    relatedLaws: [],
    communityVotes: { yea: 47800, nay: 48200, totalVoters: 96000 },
    projectedOutcome: 'likely_pass',
    officialVotes: { yea: 264, nay: 159, abstain: 0, notVoting: 12 },
    branch: 'legislative',
  },
];

// ==========================================
// SAMPLE USERS FOR FEED POSTS
// ==========================================

export const governmentUsers: User[] = [
  {
    id: 'user-policy-1',
    username: 'constitutionalist',
    displayName: 'James Madison III',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    bio: 'Constitutional law scholar. Separation of powers matters.',
    location: 'Philadelphia, PA',
    joinedDate: '2023-06-15',
    followers: 15420,
    following: 234,
    votesCount: 312,
  },
  {
    id: 'user-policy-2',
    username: 'scotus_watcher',
    displayName: 'Elena Court',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    bio: 'Supreme Court analyst. Following every case since 2010.',
    location: 'Washington, DC',
    joinedDate: '2023-08-20',
    followers: 28900,
    following: 189,
    votesCount: 456,
  },
  {
    id: 'user-policy-3',
    username: 'exec_power',
    displayName: 'Alexander Hamilton',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    bio: 'Executive branch historian. The presidency evolves.',
    location: 'New York, NY',
    joinedDate: '2023-04-10',
    followers: 12300,
    following: 567,
    votesCount: 234,
  },
  {
    id: 'user-policy-4',
    username: 'liberty_bell',
    displayName: 'Patricia Freedom',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop',
    bio: 'Civil liberties advocate. Rights for all Americans.',
    location: 'Boston, MA',
    joinedDate: '2023-09-05',
    followers: 19800,
    following: 445,
    votesCount: 389,
  },
  {
    id: 'user-policy-5',
    username: 'federal_focus',
    displayName: 'Marcus Register',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
    bio: 'Federal policy analyst. Reading the Federal Register so you don\'t have to.',
    location: 'Arlington, VA',
    joinedDate: '2023-07-22',
    followers: 8900,
    following: 123,
    votesCount: 567,
  },
  {
    id: 'user-policy-6',
    username: 'climate_voter',
    displayName: 'Sierra Green',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop',
    bio: 'Environmental policy wonk. Climate is THE issue.',
    location: 'Portland, OR',
    joinedDate: '2023-05-18',
    followers: 23400,
    following: 678,
    votesCount: 445,
  },
  {
    id: 'user-policy-7',
    username: 'border_watch',
    displayName: 'Rio Grande',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop',
    bio: 'Immigration policy tracker. Both sides of every debate.',
    location: 'El Paso, TX',
    joinedDate: '2023-03-12',
    followers: 16700,
    following: 234,
    votesCount: 289,
  },
  {
    id: 'user-policy-8',
    username: 'tech_policy',
    displayName: 'Ada Lovelace',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
    bio: 'Tech regulation expert. From antitrust to AI.',
    location: 'San Francisco, CA',
    joinedDate: '2023-10-01',
    followers: 31200,
    following: 890,
    votesCount: 234,
  },
];

// ==========================================
// 50 FEED ITEMS ACROSS ALL 3 BRANCHES
// ==========================================

// Helper to create a Bill-like object from EO for feed compatibility
function eoToBillFormat(eo: ExecutiveOrder): Bill {
  return {
    id: eo.id,
    title: eo.title,
    shortTitle: eo.shortTitle,
    status: eo.status === 'active' ? 'signed_into_law' : 'vetoed',
    chamber: 'house', // Placeholder
    sponsor: {
      id: 'potus',
      name: eo.president,
      party: eo.president.includes('Trump') ? 'R' : 'D',
      state: 'US',
      chamber: 'house',
      imageUrl: '',
    },
    introducedDate: eo.signedDate,
    lastActionDate: eo.publishedDate,
    category: eo.category,
    congressNumber: eo.eoNumber,
    congressUrl: eo.federalRegisterUrl,
    fullText: eo.fullText,
    simplifiedText: eo.simplifiedText,
    realWorldImpact: eo.realWorldImpact,
    relatedLaws: [],
    communityVotes: eo.communityVotes,
    projectedOutcome: 'likely_pass',
    branch: 'executive',
  };
}

function scotusToBillFormat(sc: SupremeCourtCase): Bill {
  return {
    id: sc.id,
    title: sc.caseName,
    shortTitle: sc.shortName,
    status: sc.status === 'decided' ? 'signed_into_law' : 'in_committee',
    chamber: 'senate', // Placeholder
    sponsor: {
      id: 'scotus',
      name: 'Supreme Court',
      party: 'I',
      state: 'US',
      chamber: 'senate',
      imageUrl: '',
    },
    introducedDate: sc.arguedDate || sc.term,
    lastActionDate: sc.decidedDate || sc.arguedDate || sc.term,
    category: sc.category,
    congressNumber: sc.docketNumber,
    congressUrl: sc.courtListenerUrl,
    fullText: sc.questionPresented,
    simplifiedText: sc.simplifiedQuestion,
    realWorldImpact: sc.realWorldImpact,
    relatedLaws: [],
    communityVotes: sc.communityVotes,
    projectedOutcome: 'uncertain',
    branch: 'judicial',
  };
}

export const governmentFeedItems: FeedItem[] = [
  // Legislative Branch Posts (20)
  {
    id: 'gov-feed-1',
    type: 'vote',
    user: governmentUsers[0],
    bill: additionalBills[0], // Inflation Reduction Act
    vote: 'yea',
    comment: 'The largest climate investment in history. Solar installations up 50% already. This is what legislation can accomplish.',
    timestamp: '2024-12-24T10:00:00Z',
    likes: 1245,
  },
  {
    id: 'gov-feed-2',
    type: 'vote',
    user: governmentUsers[1],
    bill: additionalBills[1], // Infrastructure Law
    vote: 'yea',
    comment: 'Finally fixing our crumbling bridges. 135,000 being repaired. True bipartisanship is possible.',
    timestamp: '2024-12-24T09:30:00Z',
    likes: 892,
  },
  {
    id: 'gov-feed-3',
    type: 'vote',
    user: governmentUsers[5],
    bill: additionalBills[2], // American Rescue Plan
    vote: 'nay',
    comment: 'Contributed to inflation. The stimulus checks were popular but the $1.9T price tag was too high.',
    timestamp: '2024-12-24T08:45:00Z',
    likes: 567,
  },
  {
    id: 'gov-feed-4',
    type: 'vote',
    user: governmentUsers[3],
    bill: additionalBills[3], // Gun Safety Law
    vote: 'yea',
    comment: 'First gun legislation in 30 years. Enhanced background checks for under-21 buyers is common sense.',
    timestamp: '2024-12-23T22:00:00Z',
    likes: 1456,
  },
  {
    id: 'gov-feed-5',
    type: 'vote',
    user: governmentUsers[7],
    bill: additionalBills[4], // CHIPS Act
    vote: 'yea',
    comment: 'National security requires domestic chip production. Intel, TSMC building plants here now. 50,000+ jobs.',
    timestamp: '2024-12-23T20:15:00Z',
    likes: 1123,
  },
  {
    id: 'gov-feed-6',
    type: 'vote',
    user: governmentUsers[3],
    bill: additionalBills[5], // Respect for Marriage Act
    vote: 'yea',
    comment: 'Protecting 700,000+ same-sex marriages. Love is love. Historic moment.',
    timestamp: '2024-12-23T18:30:00Z',
    likes: 2345,
  },
  {
    id: 'gov-feed-7',
    type: 'vote',
    user: governmentUsers[4],
    bill: additionalBills[6], // Women\'s Health Protection Act
    vote: 'yea',
    comment: 'We tried to codify Roe. Failed by ONE vote. One month later, Dobbs struck it down. Elections matter.',
    timestamp: '2024-12-23T16:00:00Z',
    likes: 1789,
  },
  {
    id: 'gov-feed-8',
    type: 'vote',
    user: governmentUsers[0],
    bill: additionalBills[7], // For the People Act
    vote: 'yea',
    comment: 'Automatic voter registration, end gerrymandering, campaign finance reform. Killed by filibuster.',
    timestamp: '2024-12-23T14:20:00Z',
    likes: 1567,
  },
  {
    id: 'gov-feed-9',
    type: 'vote',
    user: governmentUsers[6],
    bill: additionalBills[8], // Born-Alive Protection
    vote: 'nay',
    comment: 'This criminalizes doctors for standard medical decisions. It\'s already illegal to harm infants.',
    timestamp: '2024-12-23T12:00:00Z',
    likes: 678,
  },
  {
    id: 'gov-feed-10',
    type: 'vote',
    user: governmentUsers[3],
    bill: additionalBills[9], // Trans Athletes Ban
    vote: 'nay',
    comment: 'This targets trans kids, not elite athletes. Let kids play sports.',
    timestamp: '2024-12-23T10:30:00Z',
    likes: 1234,
  },
  {
    id: 'gov-feed-11',
    type: 'vote',
    user: governmentUsers[6],
    bill: additionalBills[10], // Laken Riley Act
    vote: 'yea',
    comment: 'Detention for immigrants charged with crimes. First bill Trump signed in 2025. Bipartisan support.',
    timestamp: '2024-12-22T22:00:00Z',
    likes: 789,
  },
  // Executive Branch Posts (15)
  {
    id: 'gov-feed-12',
    type: 'vote',
    user: governmentUsers[2],
    bill: eoToBillFormat(executiveOrders[0]), // Border Emergency
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: Border emergency declared. Military deployed. No congressional approval needed. This is executive overreach.',
    timestamp: '2024-12-22T20:00:00Z',
    likes: 1567,
  },
  {
    id: 'gov-feed-13',
    type: 'vote',
    user: governmentUsers[6],
    bill: eoToBillFormat(executiveOrders[1]), // Immigration Enforcement
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: ICE enforcement increased. Catch-and-release ended. Families being separated again.',
    timestamp: '2024-12-22T18:30:00Z',
    likes: 1234,
  },
  {
    id: 'gov-feed-14',
    type: 'vote',
    user: governmentUsers[4],
    bill: eoToBillFormat(executiveOrders[2]), // End DEI
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: All federal DEI programs eliminated. Diversity officers fired. This erases progress.',
    timestamp: '2024-12-22T16:00:00Z',
    likes: 1890,
  },
  {
    id: 'gov-feed-15',
    type: 'vote',
    user: governmentUsers[0],
    bill: eoToBillFormat(executiveOrders[3]), // End Censorship
    vote: 'yea',
    comment: 'EXECUTIVE ORDER: Government can\'t tell social media to remove content. Free speech victory.',
    timestamp: '2024-12-22T14:00:00Z',
    likes: 2134,
  },
  {
    id: 'gov-feed-16',
    type: 'vote',
    user: governmentUsers[3],
    bill: eoToBillFormat(executiveOrders[4]), // Youth Gender Care
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: Federal funding cut for trans youth healthcare. Doctors\' licenses threatened. This harms kids.',
    timestamp: '2024-12-22T12:00:00Z',
    likes: 1456,
  },
  {
    id: 'gov-feed-17',
    type: 'vote',
    user: governmentUsers[5],
    bill: eoToBillFormat(executiveOrders[5]), // Energy Independence
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: Paris Agreement withdrawal. Federal lands opened to drilling. Climate goals abandoned.',
    timestamp: '2024-12-22T10:00:00Z',
    likes: 1678,
  },
  {
    id: 'gov-feed-18',
    type: 'vote',
    user: governmentUsers[4],
    bill: eoToBillFormat(executiveOrders[6]), // Merit Hiring
    vote: 'yea',
    comment: 'EXECUTIVE ORDER: Federal hiring now merit-based only. No diversity considerations. Fair or discriminatory?',
    timestamp: '2024-12-21T22:00:00Z',
    likes: 890,
  },
  {
    id: 'gov-feed-19',
    type: 'vote',
    user: governmentUsers[0],
    bill: eoToBillFormat(executiveOrders[7]), // Travel Ban
    vote: 'nay',
    comment: 'EXECUTIVE ORDER (2017): Original travel ban. Courts blocked it. Shows limits of executive power.',
    timestamp: '2024-12-21T20:00:00Z',
    likes: 1234,
  },
  {
    id: 'gov-feed-20',
    type: 'vote',
    user: governmentUsers[5],
    bill: eoToBillFormat(executiveOrders[8]), // Biden Climate
    vote: 'yea',
    comment: 'EXECUTIVE ORDER (2021): Biden\'s climate order. Paused drilling, set clean energy goals. Now revoked by Trump.',
    timestamp: '2024-12-21T18:00:00Z',
    likes: 1567,
  },
  {
    id: 'gov-feed-21',
    type: 'vote',
    user: governmentUsers[3],
    bill: eoToBillFormat(executiveOrders[9]), // LGBTQ Protections
    vote: 'yea',
    comment: 'EXECUTIVE ORDER (2021): Extended civil rights to LGBTQ. Schools updated policies. Now revoked. Protections gone.',
    timestamp: '2024-12-21T16:00:00Z',
    likes: 1789,
  },
  // Judicial Branch Posts (15)
  {
    id: 'gov-feed-22',
    type: 'vote',
    user: governmentUsers[1],
    bill: scotusToBillFormat(supremeCourtCases[0]), // Trump Immunity
    vote: 'nay',
    comment: 'SCOTUS: Presidents now have broad immunity from prosecution. 6-3 decision. Constitution doesn\'t say this.',
    timestamp: '2024-12-21T14:00:00Z',
    likes: 2345,
  },
  {
    id: 'gov-feed-23',
    type: 'vote',
    user: governmentUsers[2],
    bill: scotusToBillFormat(supremeCourtCases[1]), // Chevron Overturned
    vote: 'yea',
    comment: 'SCOTUS: Chevron deference ended after 40 years. Courts now decide what laws mean, not agencies. Massive shift.',
    timestamp: '2024-12-21T12:00:00Z',
    likes: 1890,
  },
  {
    id: 'gov-feed-24',
    type: 'vote',
    user: governmentUsers[3],
    bill: scotusToBillFormat(supremeCourtCases[2]), // Bump Stocks
    vote: 'nay',
    comment: 'SCOTUS: Bump stocks are legal again. Vegas shooter used one to kill 60 people. Textualism over common sense.',
    timestamp: '2024-12-21T10:00:00Z',
    likes: 1567,
  },
  {
    id: 'gov-feed-25',
    type: 'vote',
    user: governmentUsers[4],
    bill: scotusToBillFormat(supremeCourtCases[3]), // Dobbs
    vote: 'nay',
    comment: 'SCOTUS (2022): Roe v. Wade overturned after 49 years. 21 states banned abortion. Women dying from delayed care.',
    timestamp: '2024-12-20T22:00:00Z',
    likes: 3456,
  },
  {
    id: 'gov-feed-26',
    type: 'vote',
    user: governmentUsers[0],
    bill: scotusToBillFormat(supremeCourtCases[4]), // Bruen - Concealed Carry
    vote: 'yea',
    comment: 'SCOTUS (2022): States must issue concealed carry permits. Second Amendment victory. NY law struck down.',
    timestamp: '2024-12-20T20:00:00Z',
    likes: 1234,
  },
  {
    id: 'gov-feed-27',
    type: 'vote',
    user: governmentUsers[1],
    bill: scotusToBillFormat(supremeCourtCases[5]), // Affirmative Action
    vote: 'nay',
    comment: 'SCOTUS (2023): Affirmative action ended. Colleges can\'t consider race. Black enrollment expected to drop 30%.',
    timestamp: '2024-12-20T18:00:00Z',
    likes: 1890,
  },
  {
    id: 'gov-feed-28',
    type: 'vote',
    user: governmentUsers[5],
    bill: scotusToBillFormat(supremeCourtCases[6]), // Student Loans
    vote: 'yea',
    comment: 'SCOTUS (2023): Biden\'s student loan forgiveness blocked. 43 million borrowers didn\'t get relief. Major questions doctrine.',
    timestamp: '2024-12-20T16:00:00Z',
    likes: 1678,
  },
  {
    id: 'gov-feed-29',
    type: 'vote',
    user: governmentUsers[3],
    bill: scotusToBillFormat(supremeCourtCases[7]), // Trans Healthcare
    vote: 'yea',
    comment: 'SCOTUS (2025): Transgender youth healthcare case argued. Decision pending. Could affect care in 24 states.',
    timestamp: '2024-12-20T14:00:00Z',
    likes: 2123,
  },
  {
    id: 'gov-feed-30',
    type: 'vote',
    user: governmentUsers[7],
    bill: scotusToBillFormat(supremeCourtCases[8]), // Age Verification
    vote: 'nay',
    comment: 'SCOTUS (2025): Texas age verification for porn sites. First Amendment concerns vs. child safety. Watch this one.',
    timestamp: '2024-12-20T12:00:00Z',
    likes: 890,
  },
  // More Mixed Posts (20)
  {
    id: 'gov-feed-31',
    type: 'comment',
    user: governmentUsers[2],
    bill: additionalBills[0],
    comment: 'Inflation Reduction Act: Medicare finally negotiating drug prices. First 10 drugs announced. Insulin $35/month. This took decades.',
    timestamp: '2024-12-19T22:00:00Z',
    likes: 1456,
  },
  {
    id: 'gov-feed-32',
    type: 'vote',
    user: governmentUsers[6],
    bill: eoToBillFormat(executiveOrders[0]),
    vote: 'yea',
    comment: 'Border security is national security. The emergency declaration is justified by the numbers.',
    timestamp: '2024-12-19T20:00:00Z',
    likes: 1123,
  },
  {
    id: 'gov-feed-33',
    type: 'vote',
    user: governmentUsers[1],
    bill: scotusToBillFormat(supremeCourtCases[0]),
    vote: 'yea',
    comment: 'Presidents need immunity to function. But this goes too far. Core powers only should be protected.',
    timestamp: '2024-12-19T18:00:00Z',
    likes: 678,
  },
  {
    id: 'gov-feed-34',
    type: 'comment',
    user: governmentUsers[4],
    bill: additionalBills[4],
    comment: 'CHIPS Act update: TSMC Arizona plant producing chips. Intel Ohio plant breaking ground. America builds again.',
    timestamp: '2024-12-19T16:00:00Z',
    likes: 890,
  },
  {
    id: 'gov-feed-35',
    type: 'vote',
    user: governmentUsers[5],
    bill: eoToBillFormat(executiveOrders[5]),
    vote: 'yea',
    comment: 'Energy independence means lower prices and national security. Drill baby drill isn\'t the answer, but neither is killing domestic production.',
    timestamp: '2024-12-19T14:00:00Z',
    likes: 567,
  },
  {
    id: 'gov-feed-36',
    type: 'vote',
    user: governmentUsers[0],
    bill: scotusToBillFormat(supremeCourtCases[1]),
    vote: 'nay',
    comment: 'Overturning Chevron was a power grab. Unelected judges now decide technical regulations they don\'t understand.',
    timestamp: '2024-12-19T12:00:00Z',
    likes: 1234,
  },
  {
    id: 'gov-feed-37',
    type: 'vote',
    user: governmentUsers[7],
    bill: additionalBills[3],
    vote: 'yea',
    comment: 'Enhanced background checks for under-21 buyers makes sense. Not perfect, but progress.',
    timestamp: '2024-12-19T10:00:00Z',
    likes: 1567,
  },
  {
    id: 'gov-feed-38',
    type: 'comment',
    user: governmentUsers[3],
    bill: scotusToBillFormat(supremeCourtCases[3]),
    comment: '2 years after Dobbs: 21 states ban abortion. Maternal mortality rising. Women traveling hundreds of miles for care. This is the reality.',
    timestamp: '2024-12-18T22:00:00Z',
    likes: 2345,
  },
  {
    id: 'gov-feed-39',
    type: 'vote',
    user: governmentUsers[2],
    bill: eoToBillFormat(executiveOrders[2]),
    vote: 'yea',
    comment: 'Federal DEI programs were ineffective. Merit should matter most. But don\'t throw out the baby with the bathwater.',
    timestamp: '2024-12-18T20:00:00Z',
    likes: 789,
  },
  {
    id: 'gov-feed-40',
    type: 'vote',
    user: governmentUsers[6],
    bill: additionalBills[10],
    vote: 'nay',
    comment: 'Laken Riley Act: Detaining people who are CHARGED, not convicted, violates due process. Tragic case but bad policy.',
    timestamp: '2024-12-18T18:00:00Z',
    likes: 1123,
  },
  {
    id: 'gov-feed-41',
    type: 'comment',
    user: governmentUsers[1],
    bill: scotusToBillFormat(supremeCourtCases[5]),
    comment: 'One year after affirmative action ended: Black enrollment at elite schools down 20-30%. Diversity declining as predicted.',
    timestamp: '2024-12-18T16:00:00Z',
    likes: 1456,
  },
  {
    id: 'gov-feed-42',
    type: 'vote',
    user: governmentUsers[4],
    bill: eoToBillFormat(executiveOrders[3]),
    vote: 'yea',
    comment: 'Government shouldn\'t be in the business of flagging speech. This EO protects all viewpoints, not just conservative ones.',
    timestamp: '2024-12-18T14:00:00Z',
    likes: 1890,
  },
  {
    id: 'gov-feed-43',
    type: 'vote',
    user: governmentUsers[5],
    bill: additionalBills[1],
    vote: 'yea',
    comment: 'Infrastructure bill delivering: 7,500 projects, every state getting billions. This is what DC should do more often.',
    timestamp: '2024-12-18T12:00:00Z',
    likes: 1234,
  },
  {
    id: 'gov-feed-44',
    type: 'vote',
    user: governmentUsers[0],
    bill: scotusToBillFormat(supremeCourtCases[4]),
    vote: 'nay',
    comment: 'Bruen decision: More guns on streets doesn\'t make us safer. New York had good reason for proper-cause requirement.',
    timestamp: '2024-12-18T10:00:00Z',
    likes: 1567,
  },
  {
    id: 'gov-feed-45',
    type: 'comment',
    user: governmentUsers[7],
    bill: eoToBillFormat(executiveOrders[4]),
    comment: 'Gender-affirming care EO: Medical decisions should be between families and doctors. Government overreach into healthcare.',
    timestamp: '2024-12-17T22:00:00Z',
    likes: 1789,
  },
  {
    id: 'gov-feed-46',
    type: 'vote',
    user: governmentUsers[3],
    bill: additionalBills[5],
    vote: 'yea',
    comment: 'Respect for Marriage Act: Protecting existing marriages from potential future court decisions. Bipartisan success.',
    timestamp: '2024-12-17T20:00:00Z',
    likes: 2123,
  },
  {
    id: 'gov-feed-47',
    type: 'vote',
    user: governmentUsers[2],
    bill: scotusToBillFormat(supremeCourtCases[6]),
    vote: 'nay',
    comment: 'Student loan decision was political. Courts don\'t usually question how presidents use congressionally granted authority.',
    timestamp: '2024-12-17T18:00:00Z',
    likes: 1345,
  },
  {
    id: 'gov-feed-48',
    type: 'vote',
    user: governmentUsers[6],
    bill: eoToBillFormat(executiveOrders[1]),
    vote: 'yea',
    comment: 'Immigration enforcement is the law. Presidents have always had discretion in priorities. This is legal.',
    timestamp: '2024-12-17T16:00:00Z',
    likes: 890,
  },
  {
    id: 'gov-feed-49',
    type: 'comment',
    user: governmentUsers[4],
    bill: additionalBills[7],
    comment: 'For the People Act would have prevented state voting restrictions. Instead we got Georgia, Texas, Florida laws. Democracy weakened.',
    timestamp: '2024-12-17T14:00:00Z',
    likes: 1678,
  },
  {
    id: 'gov-feed-50',
    type: 'vote',
    user: governmentUsers[1],
    bill: scotusToBillFormat(supremeCourtCases[2]),
    vote: 'nay',
    comment: 'Bump stocks case: 60 people died in Vegas. Shooter fired 1,000+ rounds in 10 minutes with bump stocks. Court says they\'re not machine guns. Absurd.',
    timestamp: '2024-12-17T12:00:00Z',
    likes: 2345,
  },
  // CONTROVERSIAL POSTS - EOs and SCOTUS with big voting gaps
  {
    id: 'gov-feed-51',
    type: 'vote',
    user: governmentUsers[0],
    bill: eoToBillFormat(executiveOrders[7]), // Birthright citizenship
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: Ending birthright citizenship. The 14th Amendment is CRYSTAL CLEAR: "All persons born in the United States are citizens." Federal judges already blocked this. Unconstitutional power grab.',
    timestamp: '2024-12-26T10:00:00Z',
    likes: 3456,
  },
  {
    id: 'gov-feed-52',
    type: 'vote',
    user: governmentUsers[3],
    bill: eoToBillFormat(executiveOrders[8]), // DOGE
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: Elon Musk now has access to YOUR Social Security data, tax records, and medical history. Unelected billionaires running government. What could go wrong?',
    timestamp: '2024-12-26T09:30:00Z',
    likes: 4521,
  },
  {
    id: 'gov-feed-53',
    type: 'vote',
    user: governmentUsers[4],
    bill: eoToBillFormat(executiveOrders[9]), // J6 Pardons
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: Pardoned man who beat police officer with flagpole just arrested for threatening prosecutor. 140 officers injured on Jan 6. Blue Lives only matter when convenient.',
    timestamp: '2024-12-26T09:00:00Z',
    likes: 5678,
  },
  {
    id: 'gov-feed-54',
    type: 'vote',
    user: governmentUsers[6],
    bill: eoToBillFormat(executiveOrders[9]), // J6 Pardons - opposing view
    vote: 'yea',
    comment: 'EXECUTIVE ORDER: These were political prisoners. Two-tiered justice system. BLM rioters got probation. J6 protestors got years. Finally justice.',
    timestamp: '2024-12-26T08:30:00Z',
    likes: 2890,
  },
  {
    id: 'gov-feed-55',
    type: 'vote',
    user: governmentUsers[5],
    bill: eoToBillFormat(executiveOrders[10]), // Leave WHO
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: Leaving WHO during bird flu outbreak. Next pandemic, we\'re on our own. China now controls global health policy. America First becomes America Alone.',
    timestamp: '2024-12-26T08:00:00Z',
    likes: 3421,
  },
  {
    id: 'gov-feed-56',
    type: 'vote',
    user: governmentUsers[2],
    bill: eoToBillFormat(executiveOrders[12]), // Schedule F
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: 50,000 career experts can now be fired for political reasons. Scientists who said COVID was real. Economists who said tariffs raise prices. The purge begins.',
    timestamp: '2024-12-26T07:30:00Z',
    likes: 4123,
  },
  {
    id: 'gov-feed-57',
    type: 'vote',
    user: governmentUsers[1],
    bill: scotusToBillFormat(supremeCourtCases[9]), // Title IX trans
    vote: 'yea',
    comment: 'SCOTUS: Trans students deserve to exist. 26 states trying to erase them from schools. This is about kids\' safety and dignity, not politics.',
    timestamp: '2024-12-26T07:00:00Z',
    likes: 3890,
  },
  {
    id: 'gov-feed-58',
    type: 'vote',
    user: governmentUsers[7],
    bill: scotusToBillFormat(supremeCourtCases[12]), // SB4 Immigration
    vote: 'nay',
    comment: 'SCOTUS: Texas creating its own immigration enforcement. If upheld, California could refuse to enforce federal gun laws. Federalism works both ways.',
    timestamp: '2024-12-26T06:30:00Z',
    likes: 2567,
  },
  {
    id: 'gov-feed-59',
    type: 'vote',
    user: governmentUsers[0],
    bill: scotusToBillFormat(supremeCourtCases[11]), // Planned Parenthood
    vote: 'yea',
    comment: 'SCOTUS: Texas cut Medicaid to clinics that also provide abortions. 4 million patients lost access to cancer screenings. Pro-life? This kills women.',
    timestamp: '2024-12-25T22:00:00Z',
    likes: 4567,
  },
  {
    id: 'gov-feed-60',
    type: 'comment',
    user: governmentUsers[3],
    bill: scotusToBillFormat(supremeCourtCases[10]), // NCAA
    comment: 'SCOTUS: College athletes generate $15+ BILLION but get paid $0. Coaches make $10M. Athletes can\'t even get a free meal. Modern day exploitation.',
    timestamp: '2024-12-25T20:00:00Z',
    likes: 5123,
  },
  {
    id: 'gov-feed-61',
    type: 'vote',
    user: governmentUsers[4],
    bill: eoToBillFormat(executiveOrders[11]), // End EV Mandates
    vote: 'nay',
    comment: 'EXECUTIVE ORDER: Killing EV tax credits while China dominates the market. Ford and GM invested billions. Elon Musk\'s Tesla is the only one who benefits from this chaos.',
    timestamp: '2024-12-25T18:00:00Z',
    likes: 3234,
  },
  {
    id: 'gov-feed-62',
    type: 'vote',
    user: governmentUsers[6],
    bill: eoToBillFormat(executiveOrders[7]), // Birthright citizenship - opposing
    vote: 'yea',
    comment: 'EXECUTIVE ORDER: Birth tourism is real. Pregnant women fly in, give birth, fly home. Kid is automatic citizen. No other developed country allows this. Time to close the loophole.',
    timestamp: '2024-12-25T16:00:00Z',
    likes: 2456,
  },
  {
    id: 'gov-feed-63',
    type: 'comment',
    user: governmentUsers[2],
    bill: scotusToBillFormat(supremeCourtCases[13]), // NRA case
    comment: 'SCOTUS: 9-0 ruling that government can\'t pressure companies to drop clients they don\'t like. Sotomayor wrote it. This protects ACLU and NRA equally. Rare unity.',
    timestamp: '2024-12-25T14:00:00Z',
    likes: 4890,
  },
  {
    id: 'gov-feed-64',
    type: 'vote',
    user: governmentUsers[5],
    bill: eoToBillFormat(executiveOrders[8]), // DOGE - opposing view
    vote: 'yea',
    comment: 'EXECUTIVE ORDER: Government wastes trillions. $100M for studies on shrimp running on treadmills. $36M to the WNBA. DOGE will find the fraud. About time someone did.',
    timestamp: '2024-12-25T12:00:00Z',
    likes: 2678,
  },
  {
    id: 'gov-feed-65',
    type: 'vote',
    user: governmentUsers[1],
    bill: scotusToBillFormat(supremeCourtCases[0]), // Trump immunity
    vote: 'nay',
    comment: 'SCOTUS: The immunity ruling means a president could order Seal Team 6 to assassinate a political rival and be immune. Sotomayor\'s hypothetical. Roberts didn\'t deny it.',
    timestamp: '2024-12-25T10:00:00Z',
    likes: 5432,
  },
];

// Export combined data
export const allGovernmentActions = {
  bills: additionalBills,
  executiveOrders,
  supremeCourtCases,
  justices,
  feedItems: governmentFeedItems,
  users: governmentUsers,
};
